### ISSUE TITLE
Status

### ISSUE THREAD

**Issue by TibiaBaker** [AnusReaper/BruhEye#1]
Does it still work? Would you mind writing a short tutorial on how to apply this?

**Comment by reciate** [comment]
This isn't and was never a bypass. It's a skeleton of how BattlEye's usermode module works.

**Comment by TibiaBaker** [comment]
I was under impression that since it's an emulator, it can be used to bypass BattlEye, like it is mentioned [here](https://secret.club/2020/07/06/bottleye.html):

> The following video contains a live demonstration of my BottlEye project being used in the BattlEye-protected game Fortnite. In the video I live debug fortnite while playing online to prove that BattlEye is not loaded.

**Comment by reciate** [comment]
BottlEye was a BattlEye emulator but it got patched very quickly. This rewrite is for research only.
